version: "3.8"

services:

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: rumsan-web
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api
    env_file:
      - apps/web/.env

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: rumsan-api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - apps/api/.env

  db:
    image: postgres:16
    container_name: rumsan-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: offera
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: