/**
 * Offera - Mock Data
 * Comprehensive mock data for the leave management system.
 * This file simulates what would come from a backend API.
 * Replace these with actual API calls when integrating the backend.
 */

import type {
  User,
  LeaveRequest,
  LeaveBalance,
  LeavePolicy,
  PublicHoliday,
  Notification,
  AuditEntry,
  DashboardStats,
  TeamMember,
  MonthlyLeaveData,
  DepartmentLeaveData,
} from "./types";

/* ── Mock Users (one for each role) ── */
export const mockUsers: Record<string, User> = {
  employee: {
    id: "emp-001",
    name: "Santosh Shrestha",
    email: "santosh@rumsan.com",
    avatar: "",
    role: "employee",
    department: "Engineering",
    designation: "Software Developer",
    managerId: "mgr-001",
    joinDate: "2024-03-15",
  },
  manager: {
    id: "mgr-001",
    name: "Priya Sharma",
    email: "priya@rumsan.com",
    avatar: "",
    role: "manager",
    department: "Engineering",
    designation: "Engineering Manager",
    joinDate: "2022-06-01",
  },
  admin: {
    id: "adm-001",
    name: "Raj Thapa",
    email: "raj@rumsan.com",
    avatar: "",
    role: "admin",
    department: "Human Resources",
    designation: "HR Administrator",
    joinDate: "2021-01-10",
  },
};

/* ── Mock Leave Requests ── */
export const mockLeaveRequests: LeaveRequest[] = [
  {
    id: "LR-2026-001",
    employeeId: "emp-001",
    employeeName: "Santosh Shrestha",
    employeeDepartment: "Engineering",
    leaveType: "annual",
    startDate: "2026-02-20",
    endDate: "2026-02-22",
    totalDays: 3,
    reason: "Family vacation to Pokhara",
    status: "pending",
    isHalfDay: false,
    createdAt: "2026-02-10T09:00:00Z",
    updatedAt: "2026-02-10T09:00:00Z",
  },
  {
    id: "LR-2026-002",
    employeeId: "emp-001",
    employeeName: "Santosh Shrestha",
    employeeDepartment: "Engineering",
    leaveType: "sick",
    startDate: "2026-01-15",
    endDate: "2026-01-16",
    totalDays: 2,
    reason: "Fever and cold",
    status: "approved",
    isHalfDay: false,
    createdAt: "2026-01-14T08:30:00Z",
    updatedAt: "2026-01-14T10:00:00Z",
    approvedBy: "mgr-001",
    approverComment: "Get well soon!",
  },
  {
    id: "LR-2026-003",
    employeeId: "emp-002",
    employeeName: "Anita Gurung",
    employeeDepartment: "Engineering",
    leaveType: "casual",
    startDate: "2026-02-18",
    endDate: "2026-02-18",
    totalDays: 1,
    reason: "Personal errands",
    status: "pending",
    isHalfDay: false,
    createdAt: "2026-02-12T11:00:00Z",
    updatedAt: "2026-02-12T11:00:00Z",
  },
  {
    id: "LR-2026-004",
    employeeId: "emp-003",
    employeeName: "Bikash Tamang",
    employeeDepartment: "Design",
    leaveType: "annual",
    startDate: "2026-03-01",
    endDate: "2026-03-05",
    totalDays: 5,
    reason: "Wedding ceremony",
    status: "approved",
    isHalfDay: false,
    createdAt: "2026-02-01T14:00:00Z",
    updatedAt: "2026-02-02T09:00:00Z",
    approvedBy: "mgr-001",
    approverComment: "Congratulations! Enjoy your wedding.",
  },
  {
    id: "LR-2026-005",
    employeeId: "emp-004",
    employeeName: "Sita Rai",
    employeeDepartment: "Engineering",
    leaveType: "emergency",
    startDate: "2026-02-14",
    endDate: "2026-02-14",
    totalDays: 1,
    reason: "Family emergency",
    status: "approved",
    isHalfDay: false,
    createdAt: "2026-02-14T07:00:00Z",
    updatedAt: "2026-02-14T07:30:00Z",
    approvedBy: "mgr-001",
  },
  {
    id: "LR-2026-006",
    employeeId: "emp-001",
    employeeName: "Santosh Shrestha",
    employeeDepartment: "Engineering",
    leaveType: "casual",
    startDate: "2025-12-24",
    endDate: "2025-12-25",
    totalDays: 2,
    reason: "Christmas celebration",
    status: "approved",
    isHalfDay: false,
    createdAt: "2025-12-20T10:00:00Z",
    updatedAt: "2025-12-21T09:00:00Z",
    approvedBy: "mgr-001",
  },
  {
    id: "LR-2026-007",
    employeeId: "emp-005",
    employeeName: "Dipak Adhikari",
    employeeDepartment: "Marketing",
    leaveType: "sick",
    startDate: "2026-02-17",
    endDate: "2026-02-18",
    totalDays: 2,
    reason: "Stomach infection",
    status: "pending",
    isHalfDay: false,
    createdAt: "2026-02-16T18:00:00Z",
    updatedAt: "2026-02-16T18:00:00Z",
  },
  {
    id: "LR-2026-008",
    employeeId: "emp-001",
    employeeName: "Santosh Shrestha",
    employeeDepartment: "Engineering",
    leaveType: "annual",
    startDate: "2026-01-02",
    endDate: "2026-01-03",
    totalDays: 2,
    reason: "New Year break",
    status: "rejected",
    isHalfDay: false,
    createdAt: "2025-12-28T09:00:00Z",
    updatedAt: "2025-12-29T10:00:00Z",
    approvedBy: "mgr-001",
    approverComment: "Too many team members already on leave during this period.",
  },
  {
    id: "LR-2026-009",
    employeeId: "emp-006",
    employeeName: "Nisha KC",
    employeeDepartment: "Engineering",
    leaveType: "annual",
    startDate: "2026-02-25",
    endDate: "2026-02-27",
    totalDays: 3,
    reason: "Travel plans",
    status: "pending",
    isHalfDay: false,
    createdAt: "2026-02-13T09:00:00Z",
    updatedAt: "2026-02-13T09:00:00Z",
  },
  {
    id: "LR-2026-010",
    employeeId: "emp-001",
    employeeName: "Santosh Shrestha",
    employeeDepartment: "Engineering",
    leaveType: "sick",
    startDate: "2026-02-28",
    endDate: "2026-02-28",
    totalDays: 0.5,
    reason: "Dentist appointment",
    status: "pending",
    isHalfDay: true,
    createdAt: "2026-02-14T08:00:00Z",
    updatedAt: "2026-02-14T08:00:00Z",
  },
];

/* ── Mock Leave Balances (for the current employee) ── */
export const mockLeaveBalances: LeaveBalance[] = [
  { leaveType: "annual", total: 18, used: 7, pending: 3, remaining: 8 },
  { leaveType: "sick", total: 12, used: 2, pending: 0.5, remaining: 9.5 },
  { leaveType: "casual", total: 6, used: 2, pending: 0, remaining: 4 },
  { leaveType: "emergency", total: 3, used: 0, pending: 0, remaining: 3 },
  { leaveType: "unpaid", total: 0, used: 0, pending: 0, remaining: 0 },
];

/* ── Mock Leave Policies ── */
export const mockLeavePolicies: LeavePolicy[] = [
  {
    id: "pol-001",
    leaveType: "annual",
    defaultQuota: 18,
    carryForwardLimit: 5,
    accrualRate: 1.5,
    requiresApproval: true,
    maxConsecutiveDays: 10,
    isActive: true,
  },
  {
    id: "pol-002",
    leaveType: "sick",
    defaultQuota: 12,
    carryForwardLimit: 0,
    accrualRate: 1,
    requiresApproval: true,
    maxConsecutiveDays: 5,
    isActive: true,
  },
  {
    id: "pol-003",
    leaveType: "casual",
    defaultQuota: 6,
    carryForwardLimit: 0,
    accrualRate: 0.5,
    requiresApproval: true,
    maxConsecutiveDays: 3,
    isActive: true,
  },
  {
    id: "pol-004",
    leaveType: "emergency",
    defaultQuota: 3,
    carryForwardLimit: 0,
    accrualRate: 0,
    requiresApproval: true,
    maxConsecutiveDays: 3,
    isActive: true,
  },
  {
    id: "pol-005",
    leaveType: "unpaid",
    defaultQuota: 0,
    carryForwardLimit: 0,
    accrualRate: 0,
    requiresApproval: true,
    maxConsecutiveDays: 30,
    isActive: true,
  },
];

/* ── Mock Public Holidays ── */
export const mockPublicHolidays: PublicHoliday[] = [
  { id: "hol-001", name: "New Year's Day", date: "2026-01-01", isOptional: false },
  { id: "hol-002", name: "Republic Day", date: "2026-01-26", isOptional: false },
  { id: "hol-003", name: "Maha Shivaratri", date: "2026-02-27", isOptional: false },
  { id: "hol-004", name: "Holi", date: "2026-03-14", isOptional: false },
  { id: "hol-005", name: "Nepali New Year", date: "2026-04-14", isOptional: false },
  { id: "hol-006", name: "Buddha Jayanti", date: "2026-05-12", isOptional: false },
  { id: "hol-007", name: "Independence Day", date: "2026-08-15", isOptional: false },
  { id: "hol-008", name: "Dashain", date: "2026-10-15", isOptional: false },
  { id: "hol-009", name: "Tihar", date: "2026-11-03", isOptional: false },
  { id: "hol-010", name: "Christmas", date: "2026-12-25", isOptional: true },
];

/* ── Mock Notifications ── */
export const mockNotifications: Notification[] = [
  {
    id: "notif-001",
    userId: "emp-001",
    type: "leave_approved",
    title: "Leave Approved",
    message: "Your sick leave (Jan 15-16) has been approved by Priya Sharma.",
    isRead: true,
    createdAt: "2026-01-14T10:00:00Z",
    linkTo: "/dashboard/leave/history",
  },
  {
    id: "notif-002",
    userId: "emp-001",
    type: "leave_rejected",
    title: "Leave Rejected",
    message: "Your annual leave (Jan 2-3) has been rejected. Too many team members already on leave.",
    isRead: true,
    createdAt: "2025-12-29T10:00:00Z",
    linkTo: "/dashboard/leave/history",
  },
  {
    id: "notif-003",
    userId: "mgr-001",
    type: "new_request",
    title: "New Leave Request",
    message: "Santosh Shrestha has submitted an annual leave request for Feb 20-22.",
    isRead: false,
    createdAt: "2026-02-10T09:00:00Z",
    linkTo: "/dashboard/approvals",
  },
  {
    id: "notif-004",
    userId: "mgr-001",
    type: "new_request",
    title: "New Leave Request",
    message: "Anita Gurung has submitted a casual leave request for Feb 18.",
    isRead: false,
    createdAt: "2026-02-12T11:00:00Z",
    linkTo: "/dashboard/approvals",
  },
  {
    id: "notif-005",
    userId: "adm-001",
    type: "system",
    title: "Monthly Report Ready",
    message: "The January 2026 leave utilization report is ready for review.",
    isRead: false,
    createdAt: "2026-02-01T08:00:00Z",
    linkTo: "/dashboard/reports",
  },
  {
    id: "notif-006",
    userId: "emp-001",
    type: "reminder",
    title: "Upcoming Leave",
    message: "Reminder: Your annual leave starts on Feb 20 (if approved).",
    isRead: false,
    createdAt: "2026-02-18T08:00:00Z",
  },
  {
    id: "notif-007",
    userId: "mgr-001",
    type: "new_request",
    title: "New Leave Request",
    message: "Nisha KC has submitted an annual leave request for Feb 25-27.",
    isRead: false,
    createdAt: "2026-02-13T09:00:00Z",
    linkTo: "/dashboard/approvals",
  },
  {
    id: "notif-008",
    userId: "adm-001",
    type: "balance_low",
    title: "Low Leave Balance Alert",
    message: "3 employees have less than 2 days of annual leave remaining.",
    isRead: false,
    createdAt: "2026-02-14T08:00:00Z",
  },
];

/* ── Mock Audit Trail ── */
export const mockAuditEntries: AuditEntry[] = [
  {
    id: "audit-001",
    userId: "emp-001",
    userName: "Santosh Shrestha",
    action: "LEAVE_SUBMITTED",
    details: "Submitted annual leave request LR-2026-001 for Feb 20-22",
    timestamp: "2026-02-10T09:00:00Z",
  },
  {
    id: "audit-002",
    userId: "mgr-001",
    userName: "Priya Sharma",
    action: "LEAVE_APPROVED",
    details: "Approved sick leave request LR-2026-002 for Santosh Shrestha",
    timestamp: "2026-01-14T10:00:00Z",
  },
  {
    id: "audit-003",
    userId: "mgr-001",
    userName: "Priya Sharma",
    action: "LEAVE_REJECTED",
    details: "Rejected annual leave request LR-2026-008 for Santosh Shrestha",
    timestamp: "2025-12-29T10:00:00Z",
  },
  {
    id: "audit-004",
    userId: "adm-001",
    userName: "Raj Thapa",
    action: "POLICY_UPDATED",
    details: "Updated annual leave policy - carry forward limit changed to 5 days",
    timestamp: "2026-01-05T11:00:00Z",
  },
  {
    id: "audit-005",
    userId: "adm-001",
    userName: "Raj Thapa",
    action: "BALANCE_ADJUSTED",
    details: "Manually adjusted annual leave balance for Santosh Shrestha (+2 days)",
    timestamp: "2026-01-10T14:00:00Z",
  },
];

/* ── Mock Dashboard Statistics ── */
export const mockDashboardStats: DashboardStats = {
  totalEmployees: 48,
  pendingRequests: 5,
  approvedToday: 2,
  onLeaveToday: 3,
  upcomingLeaves: 8,
  rejectedThisMonth: 1,
};

/* ── Mock Team Members ── */
export const mockTeamMembers: TeamMember[] = [
  {
    id: "emp-001",
    name: "Santosh Shrestha",
    department: "Engineering",
    designation: "Software Developer",
    isOnLeave: false,
  },
  {
    id: "emp-002",
    name: "Anita Gurung",
    department: "Engineering",
    designation: "Frontend Developer",
    isOnLeave: false,
  },
  {
    id: "emp-003",
    name: "Bikash Tamang",
    department: "Design",
    designation: "UI/UX Designer",
    isOnLeave: false,
  },
  {
    id: "emp-004",
    name: "Sita Rai",
    department: "Engineering",
    designation: "Backend Developer",
    isOnLeave: true,
    currentLeave: { leaveType: "emergency", endDate: "2026-02-14" },
  },
  {
    id: "emp-005",
    name: "Dipak Adhikari",
    department: "Marketing",
    designation: "Marketing Specialist",
    isOnLeave: false,
  },
  {
    id: "emp-006",
    name: "Nisha KC",
    department: "Engineering",
    designation: "QA Engineer",
    isOnLeave: false,
  },
  {
    id: "emp-007",
    name: "Rohan Bista",
    department: "Engineering",
    designation: "DevOps Engineer",
    isOnLeave: false,
  },
  {
    id: "emp-008",
    name: "Meena Thapa",
    department: "Design",
    designation: "Graphic Designer",
    isOnLeave: false,
  },
];

/* ── Monthly Leave Data for Charts ── */
export const mockMonthlyLeaveData: MonthlyLeaveData[] = [
  { month: "Jan", annual: 12, sick: 8, casual: 4, emergency: 1, unpaid: 0 },
  { month: "Feb", annual: 8, sick: 5, casual: 3, emergency: 2, unpaid: 1 },
  { month: "Mar", annual: 15, sick: 6, casual: 5, emergency: 0, unpaid: 0 },
  { month: "Apr", annual: 10, sick: 4, casual: 2, emergency: 1, unpaid: 0 },
  { month: "May", annual: 7, sick: 3, casual: 4, emergency: 0, unpaid: 2 },
  { month: "Jun", annual: 18, sick: 7, casual: 6, emergency: 1, unpaid: 1 },
  { month: "Jul", annual: 14, sick: 5, casual: 3, emergency: 0, unpaid: 0 },
  { month: "Aug", annual: 9, sick: 6, casual: 4, emergency: 2, unpaid: 0 },
  { month: "Sep", annual: 11, sick: 4, casual: 5, emergency: 0, unpaid: 1 },
  { month: "Oct", annual: 20, sick: 8, casual: 7, emergency: 1, unpaid: 0 },
  { month: "Nov", annual: 13, sick: 5, casual: 3, emergency: 0, unpaid: 0 },
  { month: "Dec", annual: 22, sick: 6, casual: 8, emergency: 1, unpaid: 2 },
];

/* ── Department Leave Data for Charts ── */
export const mockDepartmentLeaveData: DepartmentLeaveData[] = [
  { department: "Engineering", totalLeaves: 45, avgPerEmployee: 7.5 },
  { department: "Design", totalLeaves: 18, avgPerEmployee: 9 },
  { department: "Marketing", totalLeaves: 12, avgPerEmployee: 6 },
  { department: "Human Resources", totalLeaves: 8, avgPerEmployee: 4 },
  { department: "Finance", totalLeaves: 10, avgPerEmployee: 5 },
];

/* ── All Employees List (for admin views) ── */
export const mockAllEmployees: User[] = [
  { id: "emp-001", name: "Santosh Shrestha", email: "santosh@rumsan.com", role: "employee", department: "Engineering", designation: "Software Developer", managerId: "mgr-001", joinDate: "2024-03-15" },
  { id: "emp-002", name: "Anita Gurung", email: "anita@rumsan.com", role: "employee", department: "Engineering", designation: "Frontend Developer", managerId: "mgr-001", joinDate: "2023-08-01" },
  { id: "emp-003", name: "Bikash Tamang", email: "bikash@rumsan.com", role: "employee", department: "Design", designation: "UI/UX Designer", managerId: "mgr-001", joinDate: "2024-01-10" },
  { id: "emp-004", name: "Sita Rai", email: "sita@rumsan.com", role: "employee", department: "Engineering", designation: "Backend Developer", managerId: "mgr-001", joinDate: "2023-11-20" },
  { id: "emp-005", name: "Dipak Adhikari", email: "dipak@rumsan.com", role: "employee", department: "Marketing", designation: "Marketing Specialist", managerId: "mgr-002", joinDate: "2024-06-15" },
  { id: "emp-006", name: "Nisha KC", email: "nisha@rumsan.com", role: "employee", department: "Engineering", designation: "QA Engineer", managerId: "mgr-001", joinDate: "2024-09-01" },
  { id: "emp-007", name: "Rohan Bista", email: "rohan@rumsan.com", role: "employee", department: "Engineering", designation: "DevOps Engineer", managerId: "mgr-001", joinDate: "2023-05-01" },
  { id: "emp-008", name: "Meena Thapa", email: "meena@rumsan.com", role: "employee", department: "Design", designation: "Graphic Designer", managerId: "mgr-002", joinDate: "2024-02-15" },
  { id: "mgr-001", name: "Priya Sharma", email: "priya@rumsan.com", role: "manager", department: "Engineering", designation: "Engineering Manager", joinDate: "2022-06-01" },
  { id: "mgr-002", name: "Kiran Maharjan", email: "kiran@rumsan.com", role: "manager", department: "Design", designation: "Design Lead", joinDate: "2022-09-15" },
  { id: "adm-001", name: "Raj Thapa", email: "raj@rumsan.com", role: "admin", department: "Human Resources", designation: "HR Administrator", joinDate: "2021-01-10" },
];
