-- AlterTable
ALTER TABLE "LeaveBalance" ALTER COLUMN "total" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "remaining" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "LeaveBalanceHistory" ALTER COLUMN "total" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "used" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "remaining" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "LeaveRequest" ALTER COLUMN "totalDays" DROP DEFAULT;
